// generated by jweb-inject.py
// based on .\sample\jweb-template.html

autowatch = 1;
inlets = 1;
outlets = 1;
var SCRIPT = "let label = document.createElement('label');\n";
SCRIPT = SCRIPT + "label.textContent = 'Hello World!';\n";
SCRIPT = SCRIPT + "window.document.body.appendChild(label);\n";
SCRIPT = SCRIPT + "window.max.bindInlet('execute', function() {\n";
SCRIPT = SCRIPT + "window.max.outlet('output', 42);\n";
SCRIPT = SCRIPT + "});\n";
SCRIPT = SCRIPT + "widow.max.outlet('ready');\n";

function inject() {
  outlet(0, 'executejavascript', SCRIPT);
}
